a=1
while a<=4:
    b=1
    while b<=a:
        b=b+1
        print('%',end=' ') 
        d=1
        '''while d<=a:
            d=d+1
            print('^',end=' ')
        c=1
    while c<=a:
        c=c+1
        print('#',end=' ')
        d=1
        while d<=b:
            d=d+1
            print('^',end=' ')'''
    a=a+1
    print('8')